// Code generated by proroc-gen-graphql, DO NOT EDIT.
package user

import (
	"context"

	"github.com/graphql-go/graphql"
	"github.com/pkg/errors"
	"github.com/ysugimoto/grpc-graphql-gateway/runtime"
	"google.golang.org/grpc"
)

var (
	gql__type_GetUserResponse  *graphql.Object      // message GetUserResponse in user.proto
	gql__type_GetUserRequest   *graphql.Object      // message GetUserRequest in user.proto
	gql__input_GetUserResponse *graphql.InputObject // message GetUserResponse in user.proto
	gql__input_GetUserRequest  *graphql.InputObject // message GetUserRequest in user.proto
)

func Gql__type_GetUserResponse() *graphql.Object {
	if gql__type_GetUserResponse == nil {
		gql__type_GetUserResponse = graphql.NewObject(graphql.ObjectConfig{
			Name:        "User_Type_GetUserResponse",
			Description: `The response message containing the greetings`,
			Fields: graphql.Fields{
				"id": &graphql.Field{
					Type: graphql.Int,
				},
				"name": &graphql.Field{
					Type: graphql.String,
				},
			},
		})
	}
	return gql__type_GetUserResponse
}

func Gql__type_GetUserRequest() *graphql.Object {
	if gql__type_GetUserRequest == nil {
		gql__type_GetUserRequest = graphql.NewObject(graphql.ObjectConfig{
			Name:        "User_Type_GetUserRequest",
			Description: `The request message containing the user's name.`,
			Fields: graphql.Fields{
				"id": &graphql.Field{
					Type: graphql.NewNonNull(graphql.Int),
				},
			},
		})
	}
	return gql__type_GetUserRequest
}

func Gql__input_GetUserResponse() *graphql.InputObject {
	if gql__input_GetUserResponse == nil {
		gql__input_GetUserResponse = graphql.NewInputObject(graphql.InputObjectConfig{
			Name: "User_Input_GetUserResponse",
			Fields: graphql.InputObjectConfigFieldMap{
				"id": &graphql.InputObjectFieldConfig{
					Type: graphql.Int,
				},
				"name": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
			},
		})
	}
	return gql__input_GetUserResponse
}

func Gql__input_GetUserRequest() *graphql.InputObject {
	if gql__input_GetUserRequest == nil {
		gql__input_GetUserRequest = graphql.NewInputObject(graphql.InputObjectConfig{
			Name: "User_Input_GetUserRequest",
			Fields: graphql.InputObjectConfigFieldMap{
				"id": &graphql.InputObjectFieldConfig{
					Type: graphql.NewNonNull(graphql.Int),
				},
			},
		})
	}
	return gql__input_GetUserRequest
}

// graphql__resolver_UserService is a struct for making query, mutation and resolve fields.
// This struct must be implemented runtime.SchemaBuilder interface.
type graphql__resolver_UserService struct {

	// Automatic connection host
	host string

	// grpc dial options
	dialOptions []grpc.DialOption

	// grpc client connection.
	// this connection may be provided by user
	conn *grpc.ClientConn
}

// new_graphql_resolver_UserService creates pointer of service struct
func new_graphql_resolver_UserService(conn *grpc.ClientConn) *graphql__resolver_UserService {
	return &graphql__resolver_UserService{
		conn: conn,
		host: "localhost:50051",
		dialOptions: []grpc.DialOption{
			grpc.WithInsecure(),
		},
	}
}

// CreateConnection() returns grpc connection which user specified or newly connected and closing function
func (x *graphql__resolver_UserService) CreateConnection(ctx context.Context) (*grpc.ClientConn, func(), error) {
	// If x.conn is not nil, user injected their own connection
	if x.conn != nil {
		return x.conn, func() {}, nil
	}

	// Otherwise, this handler opens connection with specified host
	conn, err := grpc.DialContext(ctx, x.host, x.dialOptions...)
	if err != nil {
		return nil, nil, err
	}
	return conn, func() { conn.Close() }, nil
}

// GetQueries returns acceptable graphql.Fields for Query.
func (x *graphql__resolver_UserService) GetQueries(conn *grpc.ClientConn) graphql.Fields {
	return graphql.Fields{
		"get": &graphql.Field{
			Type: Gql__type_GetUserResponse(),
			Args: graphql.FieldConfigArgument{
				"id": &graphql.ArgumentConfig{
					Type: graphql.NewNonNull(graphql.Int),
				},
			},
			Resolve: func(p graphql.ResolveParams) (interface{}, error) {
				var req GetUserRequest
				if err := runtime.MarshalRequest(p.Args, &req, false); err != nil {
					return nil, errors.Wrap(err, "Failed to marshal request for get")
				}
				client := NewUserServiceClient(conn)
				resp, err := client.GetUser(p.Context, &req)
				if err != nil {
					return nil, errors.Wrap(err, "Failed to call RPC GetUser")
				}
				return resp, nil
			},
		},
	}
}

// GetMutations returns acceptable graphql.Fields for Mutation.
func (x *graphql__resolver_UserService) GetMutations(conn *grpc.ClientConn) graphql.Fields {
	return graphql.Fields{}
}

// Register package divided graphql handler "without" *grpc.ClientConn,
// therefore gRPC connection will be opened and closed automatically.
// Occasionally you may worry about open/close performance for each handling graphql request,
// then you can call RegisterUserServiceGraphqlHandler with *grpc.ClientConn manually.
func RegisterUserServiceGraphql(mux *runtime.ServeMux) error {
	return RegisterUserServiceGraphqlHandler(mux, nil)
}

// Register package divided graphql handler "with" *grpc.ClientConn.
// this function accepts your defined grpc connection, so that we reuse that and never close connection inside.
// You need to close it maunally when application will terminate.
// Otherwise, you can specify automatic opening connection with ServiceOption directive:
//
//	service UserService {
//	   option (graphql.service) = {
//	       host: "host:port"
//	       insecure: true or false
//	   };
//
//	   ...with RPC definitions
//	}
func RegisterUserServiceGraphqlHandler(mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return mux.AddHandler(new_graphql_resolver_UserService(conn))
}
